Caught TestException: Hello!
exception fell through to main()
